# Generated by Django 5.2.4 on 2025-08-05 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('stock_quantity', models.IntegerField()),
                ('cover', models.ImageField(upload_to='product_covers/')),
                ('id_Image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Nike_online.image')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nike_online.order')),
                ('id_Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nike_online.product')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cover', models.ImageField(upload_to='category_covers/')),
                ('id_Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nike_online.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('id_basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nike_online.cart')),
                ('id_Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nike_online.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='id_User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nike_online.user'),
        ),
        migrations.AddField(
            model_name='cart',
            name='id_User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nike_online.user'),
        ),
    ]
