# Generated by Django 5.2.4 on 2025-08-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nike_online', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='id_order',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='id_order',
            field=models.ManyToManyField(to='Nike_online.order'),
        ),
    ]
