# Generated by Django 5.2.4 on 2025-08-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nike_online', '0004_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
