# Generated by Django 5.2.4 on 2025-08-05 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nike_online', '0005_product_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id_Product',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Nike_online.category'),
            preserve_default=False,
        ),
    ]
