# Generated by Django 5.2.4 on 2025-08-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nike_online', '0007_remove_product_image_image_product_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
