# Generated by Django 5.2.4 on 2025-08-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nike_online', '0009_alter_image_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='id_User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='cartitems',
            old_name='id_Product',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='cartitems',
            old_name='id_basket',
            new_name='basket',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='id_User',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='id_Product',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='Product',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='id_order',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ManyToManyField(to='Nike_online.order'),
        ),
    ]
