# Generated by Django 5.2.4 on 2025-08-06 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nike_online', '0010_rename_id_user_cart_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='basket',
            new_name='cart',
        ),
    ]
