# Generated by Django 5.2.4 on 2025-08-06 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nike_online', '0011_rename_basket_cartitems_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='Product',
            new_name='product',
        ),
    ]
