# Generated by Django 5.2.4 on 2025-08-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nike_online', '0012_rename_product_cartitems_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='cart',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='cart',
            field=models.ManyToManyField(to='Nike_online.cart'),
        ),
    ]
